<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AllCountriesSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🌍 Populating 195+ countries from all continents...');
        
        $countries = $this->getCountriesData();
        
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('countries')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        
        $chunks = array_chunk($countries, 50);
        $totalInserted = 0;
        
        foreach ($chunks as $chunk) {
            DB::table('countries')->insert($chunk);
            $totalInserted += count($chunk);
            $this->command->line("✓ Inserted $totalInserted countries...");
        }
        
        $this->command->info("✅ Successfully inserted $totalInserted countries from all continents!");
    }

    private function getCountriesData(): array
    {
        return [
            // ASIA
            ['iso2' => 'AF', 'iso3' => 'AFG', 'name' => 'Afghanistan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'AZ', 'iso3' => 'AZE', 'name' => 'Azerbaijan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'BH', 'iso3' => 'BHR', 'name' => 'Bahrain', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'BD', 'iso3' => 'BGD', 'name' => 'Bangladesh', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'BT', 'iso3' => 'BTN', 'name' => 'Bhutan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'BN', 'iso3' => 'BRN', 'name' => 'Brunei', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KH', 'iso3' => 'KHM', 'name' => 'Cambodia', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'CN', 'iso3' => 'CHN', 'name' => 'China', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'GE', 'iso3' => 'GEO', 'name' => 'Georgia', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'HK', 'iso3' => 'HKG', 'name' => 'Hong Kong', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'IN', 'iso3' => 'IND', 'name' => 'India', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'ID', 'iso3' => 'IDN', 'name' => 'Indonesia', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'IR', 'iso3' => 'IRN', 'name' => 'Iran', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'IQ', 'iso3' => 'IRQ', 'name' => 'Iraq', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'IL', 'iso3' => 'ISR', 'name' => 'Israel', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'JP', 'iso3' => 'JPN', 'name' => 'Japan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'JO', 'iso3' => 'JOR', 'name' => 'Jordan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KZ', 'iso3' => 'KAZ', 'name' => 'Kazakhstan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KP', 'iso3' => 'PRK', 'name' => 'North Korea', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KR', 'iso3' => 'KOR', 'name' => 'South Korea', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KW', 'iso3' => 'KWT', 'name' => 'Kuwait', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'KG', 'iso3' => 'KGZ', 'name' => 'Kyrgyzstan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'LA', 'iso3' => 'LAO', 'name' => 'Laos', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'LB', 'iso3' => 'LBN', 'name' => 'Lebanon', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'MY', 'iso3' => 'MYS', 'name' => 'Malaysia', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'MV', 'iso3' => 'MDV', 'name' => 'Maldives', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'MM', 'iso3' => 'MMR', 'name' => 'Myanmar', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'NP', 'iso3' => 'NPL', 'name' => 'Nepal', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'OM', 'iso3' => 'OMN', 'name' => 'Oman', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'PK', 'iso3' => 'PAK', 'name' => 'Pakistan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'PS', 'iso3' => 'PSE', 'name' => 'Palestine', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'PH', 'iso3' => 'PHL', 'name' => 'Philippines', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'QA', 'iso3' => 'QAT', 'name' => 'Qatar', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'SA', 'iso3' => 'SAU', 'name' => 'Saudi Arabia', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'SG', 'iso3' => 'SGP', 'name' => 'Singapore', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'LK', 'iso3' => 'LKA', 'name' => 'Sri Lanka', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'SY', 'iso3' => 'SYR', 'name' => 'Syria', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TW', 'iso3' => 'TWN', 'name' => 'Taiwan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TJ', 'iso3' => 'TJK', 'name' => 'Tajikistan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TH', 'iso3' => 'THA', 'name' => 'Thailand', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TL', 'iso3' => 'TLS', 'name' => 'Timor-Leste', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TR', 'iso3' => 'TUR', 'name' => 'Turkey', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'TM', 'iso3' => 'TKM', 'name' => 'Turkmenistan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'AE', 'iso3' => 'ARE', 'name' => 'United Arab Emirates', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'UZ', 'iso3' => 'UZB', 'name' => 'Uzbekistan', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'VN', 'iso3' => 'VNM', 'name' => 'Vietnam', 'region' => 'Asia', 'created_at' => now()],
            ['iso2' => 'YE', 'iso3' => 'YEM', 'name' => 'Yemen', 'region' => 'Asia', 'created_at' => now()],
            
            // EUROPE
            ['iso2' => 'AL', 'iso3' => 'ALB', 'name' => 'Albania', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'AD', 'iso3' => 'AND', 'name' => 'Andorra', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'AM', 'iso3' => 'ARM', 'name' => 'Armenia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'AT', 'iso3' => 'AUT', 'name' => 'Austria', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'BY', 'iso3' => 'BLR', 'name' => 'Belarus', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'BE', 'iso3' => 'BEL', 'name' => 'Belgium', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'BA', 'iso3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'BG', 'iso3' => 'BGR', 'name' => 'Bulgaria', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'HR', 'iso3' => 'HRV', 'name' => 'Croatia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'CY', 'iso3' => 'CYP', 'name' => 'Cyprus', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'CZ', 'iso3' => 'CZE', 'name' => 'Czech Republic', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'DK', 'iso3' => 'DNK', 'name' => 'Denmark', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'EE', 'iso3' => 'EST', 'name' => 'Estonia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'FI', 'iso3' => 'FIN', 'name' => 'Finland', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'FR', 'iso3' => 'FRA', 'name' => 'France', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'DE', 'iso3' => 'DEU', 'name' => 'Germany', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'GR', 'iso3' => 'GRC', 'name' => 'Greece', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'HU', 'iso3' => 'HUN', 'name' => 'Hungary', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'IS', 'iso3' => 'ISL', 'name' => 'Iceland', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'IE', 'iso3' => 'IRL', 'name' => 'Ireland', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'IT', 'iso3' => 'ITA', 'name' => 'Italy', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'XK', 'iso3' => 'XKX', 'name' => 'Kosovo', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'LV', 'iso3' => 'LVA', 'name' => 'Latvia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'LI', 'iso3' => 'LIE', 'name' => 'Liechtenstein', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'LT', 'iso3' => 'LTU', 'name' => 'Lithuania', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'LU', 'iso3' => 'LUX', 'name' => 'Luxembourg', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'MT', 'iso3' => 'MLT', 'name' => 'Malta', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'MD', 'iso3' => 'MDA', 'name' => 'Moldova', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'MC', 'iso3' => 'MCO', 'name' => 'Monaco', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'ME', 'iso3' => 'MNE', 'name' => 'Montenegro', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'NL', 'iso3' => 'NLD', 'name' => 'Netherlands', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'NO', 'iso3' => 'NOR', 'name' => 'Norway', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'PL', 'iso3' => 'POL', 'name' => 'Poland', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'PT', 'iso3' => 'PRT', 'name' => 'Portugal', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'RO', 'iso3' => 'ROU', 'name' => 'Romania', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'RU', 'iso3' => 'RUS', 'name' => 'Russia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'SM', 'iso3' => 'SMR', 'name' => 'San Marino', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'RS', 'iso3' => 'SRB', 'name' => 'Serbia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'SK', 'iso3' => 'SVK', 'name' => 'Slovakia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'SI', 'iso3' => 'SVN', 'name' => 'Slovenia', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'ES', 'iso3' => 'ESP', 'name' => 'Spain', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'SE', 'iso3' => 'SWE', 'name' => 'Sweden', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'CH', 'iso3' => 'CHE', 'name' => 'Switzerland', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'UA', 'iso3' => 'UKR', 'name' => 'Ukraine', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'GB', 'iso3' => 'GBR', 'name' => 'United Kingdom', 'region' => 'Europe', 'created_at' => now()],
            ['iso2' => 'VA', 'iso3' => 'VAT', 'name' => 'Vatican City', 'region' => 'Europe', 'created_at' => now()],
            
            // AFRICA
            ['iso2' => 'DZ', 'iso3' => 'DZA', 'name' => 'Algeria', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'AO', 'iso3' => 'AGO', 'name' => 'Angola', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'BJ', 'iso3' => 'BEN', 'name' => 'Benin', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'BW', 'iso3' => 'BWA', 'name' => 'Botswana', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'BF', 'iso3' => 'BFA', 'name' => 'Burkina Faso', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'BI', 'iso3' => 'BDI', 'name' => 'Burundi', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CM', 'iso3' => 'CMR', 'name' => 'Cameroon', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CV', 'iso3' => 'CPV', 'name' => 'Cape Verde', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CF', 'iso3' => 'CAF', 'name' => 'Central African Republic', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'TD', 'iso3' => 'TCD', 'name' => 'Chad', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'KM', 'iso3' => 'COM', 'name' => 'Comoros', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CG', 'iso3' => 'COG', 'name' => 'Congo', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CD', 'iso3' => 'COD', 'name' => 'Democratic Republic of the Congo', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'CI', 'iso3' => 'CIV', 'name' => "Côte d'Ivoire", 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'DJ', 'iso3' => 'DJI', 'name' => 'Djibouti', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'EG', 'iso3' => 'EGY', 'name' => 'Egypt', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GQ', 'iso3' => 'GNQ', 'name' => 'Equatorial Guinea', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ER', 'iso3' => 'ERI', 'name' => 'Eritrea', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SZ', 'iso3' => 'SWZ', 'name' => 'Eswatini', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ET', 'iso3' => 'ETH', 'name' => 'Ethiopia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GA', 'iso3' => 'GAB', 'name' => 'Gabon', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GM', 'iso3' => 'GMB', 'name' => 'Gambia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GH', 'iso3' => 'GHA', 'name' => 'Ghana', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GN', 'iso3' => 'GIN', 'name' => 'Guinea', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'GW', 'iso3' => 'GNB', 'name' => 'Guinea-Bissau', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'KE', 'iso3' => 'KEN', 'name' => 'Kenya', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'LS', 'iso3' => 'LSO', 'name' => 'Lesotho', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'LR', 'iso3' => 'LBR', 'name' => 'Liberia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'LY', 'iso3' => 'LBY', 'name' => 'Libya', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MG', 'iso3' => 'MDG', 'name' => 'Madagascar', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MW', 'iso3' => 'MWI', 'name' => 'Malawi', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ML', 'iso3' => 'MLI', 'name' => 'Mali', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MR', 'iso3' => 'MRT', 'name' => 'Mauritania', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MU', 'iso3' => 'MUS', 'name' => 'Mauritius', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MA', 'iso3' => 'MAR', 'name' => 'Morocco', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'MZ', 'iso3' => 'MOZ', 'name' => 'Mozambique', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'NA', 'iso3' => 'NAM', 'name' => 'Namibia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'NE', 'iso3' => 'NER', 'name' => 'Niger', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'NG', 'iso3' => 'NGA', 'name' => 'Nigeria', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'RW', 'iso3' => 'RWA', 'name' => 'Rwanda', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ST', 'iso3' => 'STP', 'name' => 'São Tomé and Príncipe', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SN', 'iso3' => 'SEN', 'name' => 'Senegal', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SC', 'iso3' => 'SYC', 'name' => 'Seychelles', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SL', 'iso3' => 'SLE', 'name' => 'Sierra Leone', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SO', 'iso3' => 'SOM', 'name' => 'Somalia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ZA', 'iso3' => 'ZAF', 'name' => 'South Africa', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SS', 'iso3' => 'SSD', 'name' => 'South Sudan', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'SD', 'iso3' => 'SDN', 'name' => 'Sudan', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'TZ', 'iso3' => 'TZA', 'name' => 'Tanzania', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'TG', 'iso3' => 'TGO', 'name' => 'Togo', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'TN', 'iso3' => 'TUN', 'name' => 'Tunisia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'UG', 'iso3' => 'UGA', 'name' => 'Uganda', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ZM', 'iso3' => 'ZMB', 'name' => 'Zambia', 'region' => 'Africa', 'created_at' => now()],
            ['iso2' => 'ZW', 'iso3' => 'ZWE', 'name' => 'Zimbabwe', 'region' => 'Africa', 'created_at' => now()],
            
            // AMERICAS
            ['iso2' => 'AG', 'iso3' => 'ATG', 'name' => 'Antigua and Barbuda', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'AR', 'iso3' => 'ARG', 'name' => 'Argentina', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'BS', 'iso3' => 'BHS', 'name' => 'Bahamas', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'BB', 'iso3' => 'BRB', 'name' => 'Barbados', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'BZ', 'iso3' => 'BLZ', 'name' => 'Belize', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'BO', 'iso3' => 'BOL', 'name' => 'Bolivia', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'BR', 'iso3' => 'BRA', 'name' => 'Brazil', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'CA', 'iso3' => 'CAN', 'name' => 'Canada', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'CL', 'iso3' => 'CHL', 'name' => 'Chile', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'CO', 'iso3' => 'COL', 'name' => 'Colombia', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'CR', 'iso3' => 'CRI', 'name' => 'Costa Rica', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'CU', 'iso3' => 'CUB', 'name' => 'Cuba', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'DM', 'iso3' => 'DMA', 'name' => 'Dominica', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'DO', 'iso3' => 'DOM', 'name' => 'Dominican Republic', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'EC', 'iso3' => 'ECU', 'name' => 'Ecuador', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'SV', 'iso3' => 'SLV', 'name' => 'El Salvador', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'GD', 'iso3' => 'GRD', 'name' => 'Grenada', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'GT', 'iso3' => 'GTM', 'name' => 'Guatemala', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'GY', 'iso3' => 'GUY', 'name' => 'Guyana', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'HT', 'iso3' => 'HTI', 'name' => 'Haiti', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'HN', 'iso3' => 'HND', 'name' => 'Honduras', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'JM', 'iso3' => 'JAM', 'name' => 'Jamaica', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'MX', 'iso3' => 'MEX', 'name' => 'Mexico', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'NI', 'iso3' => 'NIC', 'name' => 'Nicaragua', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'PA', 'iso3' => 'PAN', 'name' => 'Panama', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'PY', 'iso3' => 'PRY', 'name' => 'Paraguay', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'PE', 'iso3' => 'PER', 'name' => 'Peru', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'KN', 'iso3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'LC', 'iso3' => 'LCA', 'name' => 'Saint Lucia', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'VC', 'iso3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'SR', 'iso3' => 'SUR', 'name' => 'Suriname', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'TT', 'iso3' => 'TTO', 'name' => 'Trinidad and Tobago', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'US', 'iso3' => 'USA', 'name' => 'United States', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'UY', 'iso3' => 'URY', 'name' => 'Uruguay', 'region' => 'Americas', 'created_at' => now()],
            ['iso2' => 'VE', 'iso3' => 'VEN', 'name' => 'Venezuela', 'region' => 'Americas', 'created_at' => now()],
            
            // OCEANIA
            ['iso2' => 'AU', 'iso3' => 'AUS', 'name' => 'Australia', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'FJ', 'iso3' => 'FJI', 'name' => 'Fiji', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'KI', 'iso3' => 'KIR', 'name' => 'Kiribati', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'MH', 'iso3' => 'MHL', 'name' => 'Marshall Islands', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'FM', 'iso3' => 'FSM', 'name' => 'Micronesia', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'NR', 'iso3' => 'NRU', 'name' => 'Nauru', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'NZ', 'iso3' => 'NZL', 'name' => 'New Zealand', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'PW', 'iso3' => 'PLW', 'name' => 'Palau', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'PG', 'iso3' => 'PNG', 'name' => 'Papua New Guinea', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'WS', 'iso3' => 'WSM', 'name' => 'Samoa', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'SB', 'iso3' => 'SLB', 'name' => 'Solomon Islands', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'TO', 'iso3' => 'TON', 'name' => 'Tonga', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'TV', 'iso3' => 'TUV', 'name' => 'Tuvalu', 'region' => 'Oceania', 'created_at' => now()],
            ['iso2' => 'VU', 'iso3' => 'VUT', 'name' => 'Vanuatu', 'region' => 'Oceania', 'created_at' => now()],
        ];
    }
}
